
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';


/* start user functions */

export const GROUP_LIST = 'GROUP_LIST'
export const FRIEND_LIST = 'FRIEND_LIST'
export const ADD_FRIEND = 'ADD_FRIEND'
export const ADD_TRIP = 'ADD_TRIP'
export const ADD_GROUP = 'ADD_GROUP'

export const REMOVE_FRIEND = 'REMOVE_FRIEND'
export const REMOVE_GROUP = 'REMOVE_GROUP'
export const REMOVE_TRIP = 'REMOVE_TRIP'


export const FETCH_GROUPS_SUCCESS = 'FETCH_GROUPS_SUCCESS'
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS'

export const FETCH_GROUPS_START = 'FETCH_GROUPS_START'
export const FETCH_FRIENDS_START = 'FETCH_FRIENDS_START'


export const FETCH_GROUP_DETAILS_START = 'FETCH_GROUP_DETAILS_START'
export const FETCH_GROUP_DETAILS_SUCCESS = 'FETCH_GROUP_DETAILS_SUCCESS'


export const ADD_FRIEND_TO_GROUP = 'ADD_FRIEND_TO_GROUP'




export const CLEAR_DETAILS = 'CLEAR_DETAILS'

/* end of user functions */


// export const GET_RECOMMENDATION = 'GET_RECOMMENDATION'